### ISSUE TITLE
Suggestions for README

### ISSUE THREAD

**Issue by Hackathorn** [bourdakos1/capsule-networks#1]
Excellent Hacker-Noon article. Dramatic and informative! Congrats... 
However, more credit (which you partially do!) should be given to the [CapsNet-Tensorflow repro](https://github.com/naturomics/CapsNet-Tensorflow) by Huadong Liao (aka Naturomics). His README is helpful. 
Question: How does the Naturomics and your repro differ from [Hinton's repro](https://github.com/XifengGuo/CapsNet-Keras)? So, it uses both Keras and TF. Why did you not use the Naturomics repro? Should mention this issue in your README.
In any case, excellent article that help me understand the significance behind capsule networks. Upgrade your README, inserting a link to your article and copying a few paragraphs at the end about how-to-use.

**Comment by bourdakos1** [comment]
Hi there and thank you for the feedback!

The repos are essentially the same, so I will definitely add a larger shout-out to Huadong Liao and link to his repo in the article.

The main difference is that the MNIST dataset is included in the repo and added a requirements.txt so that it's easier for beginners to get started. I also wanted to try and beef up my tensorflow skills and get a deeper understanding of the Capsule architecture by attempting to implement the ability to train on images that have 3 color channels (as opposed to just black and white) as well as larger than 28x28 pixels

I will definitely add a readme! I can't believe I forgot one, I feel foolish 🤦‍♂️

Again, thank you for the feedback 😄
